### ISSUE TITLE
TypeError: r.on is not a function after upgrading from 1.5.1->1.5.2

### ISSUE THREAD

**Issue by vietnugent** [perliedman/query-overpass#29]
My React app (v15.6.2) broke after upgrading query-overpass from 1.5.1 to 1.5.2.

my code
```
...
        const resultHandler = action('Fetch OSM data', (error, data) => {
            console.log("OSM Error: ", error);
            if (!error && data.features !== undefined) {
                this.osmData.replace(data.features);
                console.log("Raw OSM data: ", data);                
            }
        });
        const options = {
            overpass_url: this.backend.overpass_url,
            flatProperties: false
        }
        osmQuery(q, resultHandler, options);   
```

Error
```
TypeError: r.on is not a function
./node_modules/query-overpass/index.js.module.exports
node_modules/query-overpass/index.js:84
  81 |             });
  82 |     }
  83 | 
> 84 |     r.on('error', cb);
  85 | 
  86 |     return r;
  87 | };
```

**Comment by perliedman** [comment]
Hi and thanks for pointing this out!

This line has clearly been misplaced, and should be inside the first `if`-branch instead. I'll try to fix this ASAP.

**Comment by perliedman** [comment]
I have released version 1.5.3 that hopefully fixes this!
